Feature mvc
gids-dadi/Budget_monitor_app pull request #1
Opened 2022-10-27 13:34 UTC by gids-dadi

In this project, I created a Ruby on Rails application that allows the user to:

Register and log in, so that the data is private to them.
Introduce new transactions associated with a category.
See the money spent on each category.

2022-10-27 16:33 UTC, prolajumokeoni requested changes
Hi @gids-dadi 
Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️ No linter errors
✔️ Git flow was correctly used
✔️  Good design
✔️  Good Presentation



## Required Changes ♻️

- [ ] Based on the [project requirements](https://github.com/microverseinc/curriculum-rails/blob/main/capstone/rails_capstone.md#description) this project is a mobile web application, please follow the guidelines and make all your app pages layout look like the  [design guidelines](https://www.behance.net/gallery/19759151/Snapscan-iOs-design-and-branding?tracking_source=), please see video below to see how your application looks on mobile screen size

https://user-images.githubusercontent.com/69638013/198343071-1ae4b3e8-eb84-4a19-a8cc-89d817e4f05d.mp4


 
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-27 16:33 UTC, prolajumokeoni commented on README.md
> +View Project: (https://vast-harbor-92034.herokuapp.com/)
- [ ] Kindly ensure that all  the deployed link pages works properly, currently, this is what is shown on the link ⬇️  

![Screenshot_513](https://user-images.githubusercontent.com/69638013/198340202-04780a4a-9443-4530-ae9c-1973da7843da.png)

2022-10-27 16:33 UTC, prolajumokeoni commented on app/views/categories/new.html.erb
> +  </div>
- [ ] Kindly style the save button on the forms, currently this is not visible on the page please make the button for saving responses visible by adding appropriate styling 👍🏿

2022-10-27 16:33 UTC, prolajumokeoni commented on app/views/transactions/new.html.erb
> +  </div>
- [ ] Kindly style the save button on the forms, currently this is not visible on the page please make the button for saving responses visible by adding appropriate styling 👍🏿

2022-10-27 16:33 UTC, prolajumokeoni commented on app/views/transactions/show.html.erb
> +  </div>
- [ ] Kindly add a back button so users can easily navigate to the home page, this will create a better user experience

2022-10-28 05:02 UTC, ShoiraTa requested changes
Hi @gids-dadi ,

:thumbsup: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.

**First let me to point out:**

- Great commit history! ✔️ 
- You passed all the Linters! ✔️ 
- Professional pull request! ✔️ 

Keep on coding, good job so far! :clap:

There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media.giphy.com/media/dEPGknRiEniec/giphy.gif" width="500" height="250" />

 ## Required Changes  :recycle: 

_Check the comments under the review._ 

***
Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear by mentioning my Github username [@shoirata].


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

* * *
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 05:02 UTC, ShoiraTa commented on README.md
- [ ] Based on Project requirements, the page should be deployed and have a live version, please bring the link back  and make sure the page works as expected :) 
<img width="582" alt="Screenshot 2022-10-28 at 07 59 27" src="https://user-images.githubusercontent.com/77038610/198506381-cf7eb223-e390-4886-a6b4-27e89af5cab2.png">

2022-10-28 09:54 UTC, DammyShittu requested changes
Hi @gids-dadi,

## Highlights
✔️ Descriptive PR
✔️ Passing linters
✔️ Good branch name

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 09:54 UTC, DammyShittu commented on README.md
> +View Project:(https://budget-monitor-app.herokuapp.com/)
- [ ] Kindly ensure your app deployment is properly done.

  ![ryur](https://user-images.githubusercontent.com/54848363/198559673-a93b2b44-c772-4030-bb40-dd7d1f43e972.jpg)

2022-10-28 10:48 UTC, t-yanick approved these changes
Hi @gids-dadi, 

### Great job !!!
### To Highlight! :clap:  :green_circle: 

:heavy_check_mark:  Good commit messages
:heavy_check_mark: Descriptive Readme file

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit:  
Congratulations! 🎉 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

### N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-10-28 10:56 UTC, merged